# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: SAD-PROJECT_development
  pool: 5
  timeout: 5000
  username: jansantos
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: SAD-PROJECT_test
  pool: 5
  timeout: 5000
  username: jansantos
  password:

production:
  <<: *default
  database: SAD-PROJECT_production
